name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/package.name = .*/package.name = omnitrixvoice/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.omnitrix/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          echo "requirements = python3,kivy,speechrecognition" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.main = omnitrix.py" >> buildozer.spec
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Omnitrix-Voice-Assistant-APK
          path: bin/*.apk
