name: Build Omnitrix Assistant

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git python3 python3-venv libtool libffi-dev libssl-dev
          pip install cython buildozer

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: omnitrix-voice.apk
          path: bin/*.apk
