name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-virtualenv build-essential libffi-dev libssl-dev libjpeg-dev libsqlite3-dev libpng-dev libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libfreetype6-dev libpulse-dev libtool autoconf
        pip install buildozer cython

    - name: Initialize buildozer
      run: buildozer init

    - name: Replace default main.py with your app
      run: |
        rm main.py
        cp omnitrix.py main.py
